[project]
name = 'Decentralized-Ontological-Framework-Restructuring-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.conceptual-incompatibility-resolution]
path = 'contracts/conceptual-incompatibility-resolution.clar'
clarity_version = 2
epoch = 2.5

[contracts.logical-consistency-preservation]
path = 'contracts/logical-consistency-preservation.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-axiom-redefinition]
path = 'contracts/reality-axiom-redefinition.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
